version: '3.8'
services:  
  api:    
    build: .
    container_name: api_backend    
    ports:      
      - '4000:4000'    
    # volumes:     
    #   - ./:/app      
      # - ./home/artbot/node-compose/app/node_modules